export const LOCATION_NAMESPACE_LOCATION = 'LOCATION_NAMESPACE_LOCATION';
export const LOCATION_NAMESPACE_PIN = 'LOCATION_NAMESPACE_PIN';
export const LOCATION_NAMESPACE_SOMEONE = 'LOCATION_NAMESPACE_SOMEONE';